Add hiking osm on project page
osmbe/website pull request #131
Opened 2021-06-25 13:29 UTC by nobohan

Hello, 

This a PR for announcing the hiking-osm-be project! I'm planning to make some announcements and to "publicly" release the hiking.osm.be page beginning of next week. 

Julien

2021-06-25 13:34 UTC, jbelien requested changes

2021-06-25 13:34 UTC, jbelien commented on en/projects/hiking-osm-be.md
> +title: hiking-osm-be maps
Needs a title a bit more "sexy" 😁

2021-06-25 13:34 UTC, jbelien commented on nl/projects/hiking-osm-be.md
> +title: hiking-osm-be maps
Needs a title a bit more "sexy" 😁

2021-06-25 13:34 UTC, jbelien commented on en/projects/hiking-osm-be.md
> +This project was initiated by the two companies [Champs-Libres Coopérative](https://www.champs-libres.coop/) and the [atelier cartographique](https://atelier-cartographique.be/). More information on
```suggestion
This project was initiated by the two companies [Champs-Libres Coopérative](https://www.champs-libres.coop/) and the [atelier cartographique](https://atelier-cartographique.be/). More information on the [FAQ](https://hiking.osm.be/en/index.html#FAQ).
```

2021-06-25 13:34 UTC, jbelien commented on nl/projects/hiking-osm-be.md
> +This project was initiated by the two companies [Champs-Libres Coopérative](https://www.champs-libres.coop/) and the [atelier cartographique](https://atelier-cartographique.be/). More information on
```suggestion
This project was initiated by the two companies [Champs-Libres Coopérative](https://www.champs-libres.coop/) and the [atelier cartographique](https://atelier-cartographique.be/). More information on the [FAQ](https://hiking.osm.be/nl/index.html#FAQ).
```

2021-06-25 13:35 UTC, jbelien commented
Don't forget to translate <https://hiking.osm.be/>.

2021-06-25 14:32 UTC, jbelien approved these changes
Good to go !
Let me know when you want me to merge it 😃

2021-07-02 08:36 UTC, nobohan commented
Hello Jonathan, it is a good time to merge it. I'll make some announcements today in one hour.

2021-07-02 08:38 UTC, merged